const products = [
  {
    _id: "1",
    name: "Airpods wireless",
    image: "/images/airpods.jpg",
    description: "some description about something or other",
    brand: "Apple",
    category: "Electronics",
    price: 90,
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: "2",
    name: "alexa wireless",
    image: "/images/alexa.jpg",
    description: "some description about something or other",
    brand: "Apple",
    category: "Electronics",
    price: 95,
    countInStock: 33,
    rating: 4.2,
    numReviews: 1,
  },
  {
    _id: "3",
    name: "Camera pro1",
    image: "/images/camera.jpg",
    description: "some description about something or other",
    brand: "Nikom",
    category: "Electronics",
    price: 30,
    countInStock: 7,
    rating: 5,
    numReviews: 30,
  },
  {
    _id: "4",
    name: "wireless mouse",
    image: "/images/mouse.jpg",
    description: "some description about something or other",
    brand: "Logiteck",
    category: "Electronics",
    price: 190,
    countInStock: 7,
    rating: 3.2,
    numReviews: 1,
  },
  {
    _id: "5",
    name: "iphone 7",
    image: "/images/phone.jpg",
    description: "some description about something or other",
    brand: "Apple",
    category: "Electronics",
    price: 90,
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
];

export default products;
